<?php
//Controller is generated by MVC Schema Engine

/**
* @property CI_Loader $load
* @property CI_Form_validation $form_validation
* @property CI_Input $input
* @property CI_Email $email
* @property CI_DB_active_record $db
* @property CI_DB_forge $dbforge
* @property VehicleDBUtils $VehicleDBUtils
* @property Chi_nhanh $chi_nhanh*/ 

class c_Chi_nhanh extends Controller
{
    //message in vietnamese, TODO: add I18N later
    var $messageSuccess = "Thành công";
    var $messageFail    = "Thất bại";

    function c_Chi_nhanh()
    {
        parent::Controller();
        $this->load->model('chi_nhanh');
        $this->load->model('VehicleDBUtils');

        $this->load->helper('form');
        $this->load->helper('object2array');
        $this->load->library('form_validation');
    }

    function index()
    {
        $this->load->view('scaffolding_form/v_chi_nhanh');
    }

    function readChi_nhanh($priKey)
    {
        if(isset ($priKey))
        {
            $this->chi_nhanh->MS_CHI_NHANH = $priKey;

            $rows = $this->chi_nhanh->read();
            foreach($rows as $row)
            {
                echo $row->MS_CHI_NHANH."<br>";
                echo $row->TEN_CHI_NHANH."<br>";
            }
        }
    }

    function create()
    {
        $this->chi_nhanh->MS_CHI_NHANH = $this->input->xss_clean($this->input->post('MS_CHI_NHANH'));
        $this->chi_nhanh->TEN_CHI_NHANH = $this->input->xss_clean($this->input->post('TEN_CHI_NHANH'));
        $this->chi_nhanh->diemdiemID = $this->input->xss_clean($this->input->post('diemdiemID'));


        if($this->chi_nhanh->save())
        echo $this->messageSuccess;
        else
        echo $this->messageFail;

    }

    function read()
    {
        $this->load->view('v_chi_nhanh');
    }

    function read_json_format()
    {
        echo json_encode($this->chi_nhanh->readByPagination());
    }

    function update()
    {
        $this->chi_nhanh->MS_CHI_NHANH = $this->input->xss_clean($this->input->post('MS_CHI_NHANH'));
        $this->chi_nhanh->TEN_CHI_NHANH = $this->input->xss_clean($this->input->post('TEN_CHI_NHANH'));
        $this->chi_nhanh->diemdiemID = $this->input->xss_clean($this->input->post('diemdiemID'));

        if($this->chi_nhanh->save())
        echo $this->messageSuccess;
        else
        echo $this->messageFail;

    }

    function delete()
    {
        $this->chi_nhanh->MS_CHI_NHANH = $this->input->xss_clean($this->input->post('MS_CHI_NHANH'));

        if($this->chi_nhanh->delete())
        echo $this->messageSuccess;
        else
        echo $this->messageFail;

    }



}
?>