<?php
//Controller is generated by MVC Schema Engine

/**
* @property CI_Loader $load
* @property CI_Form_validation $form_validation
* @property CI_Input $input
* @property CI_Email $email
* @property CI_DB_active_record $db
* @property CI_DB_forge $dbforge
* @property VehicleDBUtils $VehicleDBUtils
* @property Metadata $metadata*/ 

class c_Metadata extends Controller
{
    //message in vietnamese, TODO: add I18N later
    var $messageSuccess = "Thành công";
    var $messageFail    = "Thất bại";

    function c_Metadata()
    {
         parent::Controller();
         $this->load->model('metadata');
         $this->load->model('VehicleDBUtils');

         $this->load->helper('form');
         $this->load->helper('object2array');
         $this->load->library('form_validation');
    }

    function index()
    {       
        $this->load->view('scaffolding_form/v_metadata');        
    }  

    function readMetadata($priKey)
    {
        if(isset ($priKey))
        {
                   $this->metadata->id = $priKey;
                                                
            $rows = $this->metadata->read();
            foreach($rows as $row)
            {
                        echo $row->id."<br>";
                        echo $row->tablename."<br>";
                        echo $row->use_scaffolding."<br>";
                        }
         }
    }

    function create()
    {
                        $this->metadata->tablename = $this->input->xss_clean($this->input->post('tablename'));
                    $this->metadata->use_scaffolding = $this->input->xss_clean($this->input->post('use_scaffolding'));
            
    if($this->metadata->save())
        echo $this->messageSuccess;
    else
        echo $this->messageFail;         
      
    }

    function read()
    {
        //$data['objects'] = $this->metadata->read();
        $data['form_view'] = $this->get_form_view();
        $this->load->view('v_metadata',$data);
    }

    function read_json_format()
    {
        echo json_encode($this->metadata->readByPagination());
    }

    function update()
    {
        $this->metadata->id = $this->input->xss_clean($this->input->post('id'));
        $this->metadata->tablename = $this->input->xss_clean($this->input->post('tablename'));
        $this->metadata->use_scaffolding = $this->input->xss_clean($this->input->post('use_scaffolding'));
           
        if($this->metadata->save())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;
        
    }

    function delete()
    {
            $this->metadata->id = $this->input->xss_clean($this->input->post('id'));
                        
        if($this->metadata->delete())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;
        
    }


    
}
?>