<?php
//Controller is generated by MVC Schema Engine

/**
* @property CI_Loader $load
* @property CI_Form_validation $form_validation
* @property CI_Input $input
* @property CI_Email $email
* @property CI_DB_active_record $db
* @property CI_DB_forge $dbforge
* @property VehicleDBUtils $VehicleDBUtils
* @property Model_xe $model_xe*/ 

class c_Model_xe extends Controller
{
    //message in vietnamese, TODO: add I18N later
    var $messageSuccess = "Thành công";
    var $messageFail    = "Thất bại";

    function c_Model_xe()
    {
        parent::Controller();
        $this->load->model('model_xe');
        $this->load->model('VehicleDBUtils');

        $this->load->helper('form');
        $this->load->helper('object2array');
        $this->load->library('form_validation');
    }

    function index()
    {
        $this->load->view('scaffolding_form/v_model_xe');
    }

    function readModel_xe($priKey)
    {
        if($priKey)
        {
            $this->model_xe->MS_MODEL_XE = $priKey;

            $rows = $this->model_xe->read();
            if(sizeof($rows) == 1){
                echo json_encode($rows[0]);
            }
//            foreach($rows as $row)
//            {
//                echo $row->STT_MODEL_XE."<br>";
//                echo $row->MS_MODEL_XE."<br>";
//                echo $row->LOAI_MODEL."<br>";
//                echo $row->NHAN_HIEU."<br>";
//                echo $row->MS_THUE."<br>";
//                echo $row->FUEL."<br>";
//                echo $row->PTAC."<br>";
//                echo $row->PAYLOAD."<br>";
//                echo $row->FLOOR_AREA."<br>";
//                echo $row->GENRE."<br>";
//                echo $row->SO_SUON."<br>";
//                echo $row->KM_METER_AVAILABLE."<br>";
//            }
        }
    }

    function create()
    {
        $this->model_xe->MS_MODEL_XE = $this->input->xss_clean($this->input->post('MS_MODEL_XE'));
        $this->model_xe->LOAI_MODEL = $this->input->xss_clean($this->input->post('LOAI_MODEL'));
        $this->model_xe->NHAN_HIEU = $this->input->xss_clean($this->input->post('NHAN_HIEU'));
        $this->model_xe->MS_THUE = $this->input->xss_clean($this->input->post('MS_THUE'));
        $this->model_xe->FUEL = $this->input->xss_clean($this->input->post('FUEL'));
        $this->model_xe->PTAC = $this->input->xss_clean($this->input->post('PTAC'));
        $this->model_xe->PAYLOAD = $this->input->xss_clean($this->input->post('PAYLOAD'));
        $this->model_xe->FLOOR_AREA = $this->input->xss_clean($this->input->post('FLOOR_AREA'));
        $this->model_xe->GENRE = $this->input->xss_clean($this->input->post('GENRE'));
        $this->model_xe->SO_SUON = $this->input->xss_clean($this->input->post('SO_SUON'));
        $this->model_xe->KM_METER_AVAILABLE = $this->input->xss_clean($this->input->post('KM_METER_AVAILABLE'));

        if($this->model_xe->save())
        echo $this->messageSuccess;
        else
        echo $this->messageFail;

    }

    function read()
    {
        //$data['objects'] = $this->model_xe->read();
        $data['form_view'] = $this->get_form_view();
        $this->load->view('v_model_xe',$data);
    }

    function read_json_format()
    {
        echo json_encode($this->model_xe->readByPagination());
    }

    function update()
    {
        $this->model_xe->STT_MODEL_XE = $this->input->xss_clean($this->input->post('STT_MODEL_XE'));
        $this->model_xe->MS_MODEL_XE = $this->input->xss_clean($this->input->post('MS_MODEL_XE'));
        $this->model_xe->LOAI_MODEL = $this->input->xss_clean($this->input->post('LOAI_MODEL'));
        $this->model_xe->NHAN_HIEU = $this->input->xss_clean($this->input->post('NHAN_HIEU'));
        $this->model_xe->MS_THUE = $this->input->xss_clean($this->input->post('MS_THUE'));
        $this->model_xe->FUEL = $this->input->xss_clean($this->input->post('FUEL'));
        $this->model_xe->PTAC = $this->input->xss_clean($this->input->post('PTAC'));
        $this->model_xe->PAYLOAD = $this->input->xss_clean($this->input->post('PAYLOAD'));
        $this->model_xe->FLOOR_AREA = $this->input->xss_clean($this->input->post('FLOOR_AREA'));
        $this->model_xe->GENRE = $this->input->xss_clean($this->input->post('GENRE'));
        $this->model_xe->SO_SUON = $this->input->xss_clean($this->input->post('SO_SUON'));
        $this->model_xe->KM_METER_AVAILABLE = $this->input->xss_clean($this->input->post('KM_METER_AVAILABLE'));

        if($this->model_xe->save())
        echo $this->messageSuccess;
        else
        echo $this->messageFail;

    }

    function delete()
    {
        $this->model_xe->STT_MODEL_XE = $this->input->xss_clean($this->input->post('STT_MODEL_XE'));

        if($this->model_xe->delete())
        echo $this->messageSuccess;
        else
        echo $this->messageFail;

    }



}
?>