<?php
//Controller is generated by MVC Schema Engine

/**
* @property CI_Loader $load
* @property CI_Form_validation $form_validation
* @property CI_Input $input
* @property CI_Email $email
* @property CI_DB_active_record $db
* @property CI_DB_forge $dbforge
* @property VehicleDBUtils $VehicleDBUtils
* @property Nhat_ki_hanh_trinh $nhat_ki_hanh_trinh*/ 

class c_Nhat_ki_hanh_trinh extends Controller
{
    //message in vietnamese, TODO: add I18N later
    var $messageSuccess = "Thành công";
    var $messageFail    = "Thất bại";

    function c_Nhat_ki_hanh_trinh()
    {
         parent::Controller();
         $this->load->model('nhat_ki_hanh_trinh');
         $this->load->model('VehicleDBUtils');

         $this->load->helper('form');
         $this->load->helper('object2array');
         $this->load->library('form_validation');
    }

    function index()
    {       
        $this->load->view('scaffolding_form/v_nhat_ki_hanh_trinh');        
    }  

    function readNhat_ki_hanh_trinh($priKey)
    {
        if(isset ($priKey))
        {
                   $this->nhat_ki_hanh_trinh->STT_NKHT = $priKey;
                                                                                                                                
            $rows = $this->nhat_ki_hanh_trinh->read();
            foreach($rows as $row)
            {
                        echo $row->STT_NKHT."<br>";
                        echo $row->SO_DANG_KY_XE."<br>";
                        echo $row->TEN."<br>";
                        echo $row->diemdiemKH."<br>";
                        echo $row->diemdiemKT."<br>";
                        echo $row->NGAY_KHOI_HANH."<br>";
                        echo $row->NGAY_KET_THUC_DK."<br>";
                        echo $row->NGAY_KET_THUC."<br>";
                        }
         }
    }

    function create()
    {
                        $this->nhat_ki_hanh_trinh->SO_DANG_KY_XE = $this->input->xss_clean($this->input->post('SO_DANG_KY_XE'));
                    $this->nhat_ki_hanh_trinh->TEN = $this->input->xss_clean($this->input->post('TEN'));
                    $this->nhat_ki_hanh_trinh->diemdiemKH = $this->input->xss_clean($this->input->post('diemdiemKH'));
                    $this->nhat_ki_hanh_trinh->diemdiemKT = $this->input->xss_clean($this->input->post('diemdiemKT'));
                    $this->nhat_ki_hanh_trinh->NGAY_KHOI_HANH = $this->input->xss_clean($this->input->post('NGAY_KHOI_HANH'));
                    $this->nhat_ki_hanh_trinh->NGAY_KET_THUC_DK = $this->input->xss_clean($this->input->post('NGAY_KET_THUC_DK'));
                    $this->nhat_ki_hanh_trinh->NGAY_KET_THUC = $this->input->xss_clean($this->input->post('NGAY_KET_THUC'));
            
    if($this->nhat_ki_hanh_trinh->save())
        echo $this->messageSuccess;
    else
        echo $this->messageFail;         
      
    }

    function read()
    {
        $this->load->view('v_nhat_ki_hanh_trinh');
    }

    function read_json_format()
    {
        echo json_encode($this->nhat_ki_hanh_trinh->readByPagination());
    }

    function update()
    {
        $this->nhat_ki_hanh_trinh->STT_NKHT = $this->input->xss_clean($this->input->post('STT_NKHT'));
        $this->nhat_ki_hanh_trinh->SO_DANG_KY_XE = $this->input->xss_clean($this->input->post('SO_DANG_KY_XE'));
        $this->nhat_ki_hanh_trinh->TEN = $this->input->xss_clean($this->input->post('TEN'));
        $this->nhat_ki_hanh_trinh->diemdiemKH = $this->input->xss_clean($this->input->post('diemdiemKH'));
        $this->nhat_ki_hanh_trinh->diemdiemKT = $this->input->xss_clean($this->input->post('diemdiemKT'));
        $this->nhat_ki_hanh_trinh->NGAY_KHOI_HANH = $this->input->xss_clean($this->input->post('NGAY_KHOI_HANH'));
        $this->nhat_ki_hanh_trinh->NGAY_KET_THUC_DK = $this->input->xss_clean($this->input->post('NGAY_KET_THUC_DK'));
        $this->nhat_ki_hanh_trinh->NGAY_KET_THUC = $this->input->xss_clean($this->input->post('NGAY_KET_THUC'));
           
        if($this->nhat_ki_hanh_trinh->save())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;
        
    }

    function delete()
    {
            $this->nhat_ki_hanh_trinh->STT_NKHT = $this->input->xss_clean($this->input->post('STT_NKHT'));
                                                                
        if($this->nhat_ki_hanh_trinh->delete())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;
        
    }


    
}
?>