<?php
//Model is generated by MVC Schema Engine

/**
* @property CI_Loader $load
* @property CI_Input $input
* @property CI_DB_active_record $db
* @property CI_DB_forge $dbforge
*/ 

class Chi_nhanh extends Model {

    //Type: String
    var $MS_CHI_NHANH = '';

    //Type: String
    var $TEN_CHI_NHANH = '';

    var $diemdiemID;


    function Chi_nhanh()
    {
        parent::Model();
    }

    function read()
    {
        // BEGIN FILTER CRITERIA CHECK
        // If any of the following properties are set before Chi_nhanh->get() is called from the controller then we will include
        // a where statement for each of the properties that have been set.

        if ($this->MS_CHI_NHANH)
        {
            $this->db->where("MS_CHI_NHANH", $this->MS_CHI_NHANH);
        }
        if ($this->TEN_CHI_NHANH)
        {
            $this->db->where("TEN_CHI_NHANH", $this->TEN_CHI_NHANH);
        }

        // END FILTER CRITERIA CHECK

        // This will execute the query and collect the results and other properties of the query into an object.
        $query = $this->db->get("chi_nhanh");

        return $query->result();
    }


    //TODO: check XSS and SQL injection here
    function readByPagination()
    {
        $limit = $this->input->post('rows');
        $page = $this->input->post('page');
        $sidx = $this->input->post('sidx');
        $sord = $this->input->post('sord');

        if(!$sidx) $sidx =1;
        $count = $this->db->count_all('chi_nhanh');

        if( $count >0 ) {
            $total_pages = ceil($count/$limit);
        } else {
            $total_pages = 0;
        }
        if ($page > $total_pages)
        $page=$total_pages;
        $start = $limit * $page - $limit;

        $this->db->limit($limit, $start);
        $this->db->order_by("$sidx", "$sord");
        $objects = $this->db->get("chi_nhanh")->result();
        $rows =  array();

        foreach($objects as $obj)
        {
            $cell = array();
            array_push($cell, $obj->MS_CHI_NHANH);
            array_push($cell, $obj->TEN_CHI_NHANH);
            array_push($cell, $obj->diemdiemID);
            $row = new stdClass();
            $row->id = $cell[0];
            $row->cell = $cell;
            array_push($rows, $row);
        }

        $jsonObject = new stdClass();
        $jsonObject->page =  $page;
        $jsonObject->total = $total_pages;
        $jsonObject->records = $count;
        $jsonObject->rows = $rows;



        return $jsonObject;
    }

    function save()
    {
        // When we insert or update a record in CodeIgniter, we pass the results as an array:
        $db_array = array(
                "MS_CHI_NHANH" => $this->MS_CHI_NHANH,
                 "TEN_CHI_NHANH" => $this->TEN_CHI_NHANH,
                 "diemdiemID" => $this->diemdiemID

        );

        $saveSuccess = false;
        $alreadyHave = false;

        
        $rows = $this->db->get_where("chi_nhanh", array( "MS_CHI_NHANH" => $this->MS_CHI_NHANH))->result();
        if(sizeof($rows)==1){
            $alreadyHave = true;
            echo "Trung khoa ".$this->MS_CHI_NHANH;
            return false;
        }

        if(!$alreadyHave)
        {
            $this->db->trans_start();
            $this->db->insert("chi_nhanh", $db_array);
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
            $this->db->trans_complete();
        }

        return $saveSuccess;
    }


    function delete()
    {
        $saveSuccess = false;
        // As long as chi_nhanh->MS_CHI_NHANH was set in the controller, we will delete the record.
        if ($this->MS_CHI_NHANH) {
            $this->db->where("MS_CHI_NHANH", $this->MS_CHI_NHANH);
            $this->db->delete("chi_nhanh");
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
        }
        return $saveSuccess;
    }
}

?>