<?php
//Model is generated by MVC Schema Engine

/**
* @property CI_Loader $load
* @property CI_Input $input
* @property CI_DB_active_record $db
* @property CI_DB_forge $dbforge
*/ 

class Diadiem extends Model {

      //Type: Long
    var $diemdiemID = '';

	  //Type: Float
    var $lat = '';

	  //Type: Float
    var $lon = '';

	  //Type: String
    var $diachi = '';

	
    function Diadiem()
    {
        parent::Model();
    }

    function read()
    {
        // BEGIN FILTER CRITERIA CHECK
        // If any of the following properties are set before Diadiem->get() is called from the controller then we will include
        // a where statement for each of the properties that have been set.

                if ($this->diemdiemID)
        {
            $this->db->where("diemdiemID", $this->diemdiemID);
        }
                if ($this->lat)
        {
            $this->db->where("lat", $this->lat);
        }
                if ($this->lon)
        {
            $this->db->where("lon", $this->lon);
        }
                if ($this->diachi)
        {
            $this->db->where("diachi", $this->diachi);
        }
        
        // END FILTER CRITERIA CHECK

        // This will execute the query and collect the results and other properties of the query into an object.
        $query = $this->db->get("diadiem");

        return $query->result();
    }


    //TODO: check XSS and SQL injection here
    function readByPagination()
    {
        $limit = $this->input->post('rows');
        $page = $this->input->post('page');
        $sidx = $this->input->post('sidx');
        $sord = $this->input->post('sord');

        if(!$sidx) $sidx =1;
        $count = $this->db->count_all('diadiem');

        if( $count >0 ) {
            $total_pages = ceil($count/$limit);
        } else {
            $total_pages = 0;
        }
        if ($page > $total_pages)
            $page=$total_pages;
        $start = $limit * $page - $limit;

        $this->db->limit($limit, $start);
        $this->db->order_by("$sidx", "$sord");
        $objects = $this->db->get("diadiem")->result();
        $rows =  array();

        foreach($objects as $obj)
        {
            $cell = array();
                            array_push($cell, $obj->diemdiemID);
                            array_push($cell, $obj->lat);
                            array_push($cell, $obj->lon);
                            array_push($cell, $obj->diachi);
                        $row = new stdClass();
            $row->id = $cell[0];
            $row->cell = $cell;
            array_push($rows, $row);
        }

        $jsonObject = new stdClass();
        $jsonObject->page =  $page;
        $jsonObject->total = $total_pages;
        $jsonObject->records = $count;
        $jsonObject->rows = $rows;      



        return $jsonObject;
    }

    function save()
    {
        // When we insert or update a record in CodeIgniter, we pass the results as an array:
        $db_array = array(
                    "lat" => $this->lat,
                    "lon" => $this->lon,
                    "diachi" => $this->diachi,
          );

      $saveSuccess = false;

         // If key was set in the controller, then we will update an existing record.
        if ($this->diemdiemID)
        {
            $this->db->trans_start();
            $this->db->where("diemdiemID", $this->diemdiemID);
            $this->db->update("diadiem", $db_array);
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
            $this->db->trans_complete();
        }
         // If key was not set in the controller, then we will insert a new record.
        else
        {
            $this->db->trans_start();
            $this->db->insert("diadiem", $db_array);
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
            $this->db->trans_complete();
         }
    
        return $saveSuccess;
    }


    function delete()
    {
        $saveSuccess = false;
         // As long as diadiem->diemdiemID was set in the controller, we will delete the record.
        if ($this->diemdiemID) {
            $this->db->where("diemdiemID", $this->diemdiemID);
            $this->db->delete("diadiem");
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
        }
            return $saveSuccess;
    }
}

?>