<?php
//Model is generated by MVC Schema Engine

/**
* @property CI_Loader $load
* @property CI_Input $input
* @property CI_DB_active_record $db
* @property CI_DB_forge $dbforge
*/ 

class Model_xe extends Model {

      //Type: Long
    var $STT_MODEL_XE = '';

	  //Type: String
    var $MS_MODEL_XE = '';

	  //Type: String
    var $LOAI_MODEL = '';

	  //Type: String
    var $NHAN_HIEU = '';

	  //Type: String
    var $MS_THUE = '';

	  //Type: String
    var $FUEL = '';

	  //Type: Double
    var $PTAC = '';

	  //Type: Double
    var $PAYLOAD = '';

	  //Type: Float
    var $FLOOR_AREA = '';

	  //Type: String
    var $GENRE = '';

	  //Type: String
    var $SO_SUON = '';

	  //Type: Double
    var $KM_METER_AVAILABLE = '';

	
    function Model_xe()
    {
        parent::Model();
    }

    function read()
    {
        // BEGIN FILTER CRITERIA CHECK
        // If any of the following properties are set before Model_xe->get() is called from the controller then we will include
        // a where statement for each of the properties that have been set.

                if ($this->STT_MODEL_XE)
        {
            $this->db->where("STT_MODEL_XE", $this->STT_MODEL_XE);
        }
                if ($this->MS_MODEL_XE)
        {
            $this->db->where("MS_MODEL_XE", $this->MS_MODEL_XE);
        }
                if ($this->LOAI_MODEL)
        {
            $this->db->where("LOAI_MODEL", $this->LOAI_MODEL);
        }
                if ($this->NHAN_HIEU)
        {
            $this->db->where("NHAN_HIEU", $this->NHAN_HIEU);
        }
                if ($this->MS_THUE)
        {
            $this->db->where("MS_THUE", $this->MS_THUE);
        }
                if ($this->FUEL)
        {
            $this->db->where("FUEL", $this->FUEL);
        }
                if ($this->PTAC)
        {
            $this->db->where("PTAC", $this->PTAC);
        }
                if ($this->PAYLOAD)
        {
            $this->db->where("PAYLOAD", $this->PAYLOAD);
        }
                if ($this->FLOOR_AREA)
        {
            $this->db->where("FLOOR_AREA", $this->FLOOR_AREA);
        }
                if ($this->GENRE)
        {
            $this->db->where("GENRE", $this->GENRE);
        }
                if ($this->SO_SUON)
        {
            $this->db->where("SO_SUON", $this->SO_SUON);
        }
                if ($this->KM_METER_AVAILABLE)
        {
            $this->db->where("KM_METER_AVAILABLE", $this->KM_METER_AVAILABLE);
        }
        
        // END FILTER CRITERIA CHECK

        // This will execute the query and collect the results and other properties of the query into an object.
        $query = $this->db->get("model_xe");

        return $query->result();
    }


    //TODO: check XSS and SQL injection here
    function readByPagination()
    {
        $limit = $this->input->post('rows');
        $page = $this->input->post('page');
        $sidx = $this->input->post('sidx');
        $sord = $this->input->post('sord');

        if(!$sidx) $sidx =1;
        $count = $this->db->count_all('model_xe');

        if( $count >0 ) {
            $total_pages = ceil($count/$limit);
        } else {
            $total_pages = 0;
        }
        if ($page > $total_pages)
            $page=$total_pages;
        $start = $limit * $page - $limit;

        $this->db->limit($limit, $start);
        $this->db->order_by("$sidx", "$sord");
        $objects = $this->db->get("model_xe")->result();
        $rows =  array();

        foreach($objects as $obj)
        {
            $cell = array();
                            array_push($cell, $obj->STT_MODEL_XE);
                            array_push($cell, $obj->MS_MODEL_XE);
                            array_push($cell, $obj->LOAI_MODEL);
                            array_push($cell, $obj->NHAN_HIEU);
                            array_push($cell, $obj->MS_THUE);
                            array_push($cell, $obj->FUEL);
                            array_push($cell, $obj->PTAC);
                            array_push($cell, $obj->PAYLOAD);
                            array_push($cell, $obj->FLOOR_AREA);
                            array_push($cell, $obj->GENRE);
                            array_push($cell, $obj->SO_SUON);
                            array_push($cell, $obj->KM_METER_AVAILABLE);
                        $row = new stdClass();
            $row->id = $cell[0];
            $row->cell = $cell;
            array_push($rows, $row);
        }

        $jsonObject = new stdClass();
        $jsonObject->page =  $page;
        $jsonObject->total = $total_pages;
        $jsonObject->records = $count;
        $jsonObject->rows = $rows;      



        return $jsonObject;
    }

    function save()
    {
        // When we insert or update a record in CodeIgniter, we pass the results as an array:
        $db_array = array(
                    "MS_MODEL_XE" => $this->MS_MODEL_XE,
                    "LOAI_MODEL" => $this->LOAI_MODEL,
                    "NHAN_HIEU" => $this->NHAN_HIEU,
                    "MS_THUE" => $this->MS_THUE,
                    "FUEL" => $this->FUEL,
                    "PTAC" => $this->PTAC,
                    "PAYLOAD" => $this->PAYLOAD,
                    "FLOOR_AREA" => $this->FLOOR_AREA,
                    "GENRE" => $this->GENRE,
                    "SO_SUON" => $this->SO_SUON,
                    "KM_METER_AVAILABLE" => $this->KM_METER_AVAILABLE,
          );

      $saveSuccess = false;

         // If key was set in the controller, then we will update an existing record.
        if ($this->STT_MODEL_XE)
        {
            $this->db->trans_start();
            $this->db->where("STT_MODEL_XE", $this->STT_MODEL_XE);
            $this->db->update("model_xe", $db_array);
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
            $this->db->trans_complete();
        }
         // If key was not set in the controller, then we will insert a new record.
        else
        {
            $this->db->trans_start();
            $this->db->insert("model_xe", $db_array);
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
            $this->db->trans_complete();
         }
            
        return $saveSuccess;
    }


    function delete()
    {
        $saveSuccess = false;
         // As long as model_xe->STT_MODEL_XE was set in the controller, we will delete the record.
        if ($this->STT_MODEL_XE) {
            $this->db->where("STT_MODEL_XE", $this->STT_MODEL_XE);
            $this->db->delete("model_xe");
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
        }
                    return $saveSuccess;
    }
}

?>