<?php
//Model is generated by MVC Schema Engine

/**
* @property CI_Loader $load
* @property CI_Input $input
* @property CI_DB_active_record $db
* @property CI_DB_forge $dbforge
*/ 

class Nhat_ki_hanh_trinh extends Model {

      //Type: Long
    var $STT_NKHT = '';

	  //Type: Long
    var $SO_DANG_KY_XE = '';

	  //Type: String
    var $TEN = '';

	  //Type: Long
    var $diemdiemKH = '';

	  //Type: Long
    var $diemdiemKT = '';

	  //Type: 
    var $NGAY_KHOI_HANH = '';

	  //Type: 
    var $NGAY_KET_THUC_DK = '';

	  //Type: 
    var $NGAY_KET_THUC = '';

	
    function Nhat_ki_hanh_trinh()
    {
        parent::Model();
    }

    function read()
    {
        // BEGIN FILTER CRITERIA CHECK
        // If any of the following properties are set before Nhat_ki_hanh_trinh->get() is called from the controller then we will include
        // a where statement for each of the properties that have been set.

                if ($this->STT_NKHT)
        {
            $this->db->where("STT_NKHT", $this->STT_NKHT);
        }
                if ($this->SO_DANG_KY_XE)
        {
            $this->db->where("SO_DANG_KY_XE", $this->SO_DANG_KY_XE);
        }
                if ($this->TEN)
        {
            $this->db->where("TEN", $this->TEN);
        }
                if ($this->diemdiemKH)
        {
            $this->db->where("diemdiemKH", $this->diemdiemKH);
        }
                if ($this->diemdiemKT)
        {
            $this->db->where("diemdiemKT", $this->diemdiemKT);
        }
                if ($this->NGAY_KHOI_HANH)
        {
            $this->db->where("NGAY_KHOI_HANH", $this->NGAY_KHOI_HANH);
        }
                if ($this->NGAY_KET_THUC_DK)
        {
            $this->db->where("NGAY_KET_THUC_DK", $this->NGAY_KET_THUC_DK);
        }
                if ($this->NGAY_KET_THUC)
        {
            $this->db->where("NGAY_KET_THUC", $this->NGAY_KET_THUC);
        }
        
        // END FILTER CRITERIA CHECK

        // This will execute the query and collect the results and other properties of the query into an object.
        $query = $this->db->get("nhat_ki_hanh_trinh");

        return $query->result();
    }


    //TODO: check XSS and SQL injection here
    function readByPagination()
    {
        $limit = $this->input->post('rows');
        $page = $this->input->post('page');
        $sidx = $this->input->post('sidx');
        $sord = $this->input->post('sord');

        if(!$sidx) $sidx =1;
        $count = $this->db->count_all('nhat_ki_hanh_trinh');

        if( $count >0 ) {
            $total_pages = ceil($count/$limit);
        } else {
            $total_pages = 0;
        }
        if ($page > $total_pages)
            $page=$total_pages;
        $start = $limit * $page - $limit;

        $this->db->limit($limit, $start);
        $this->db->order_by("$sidx", "$sord");
        $objects = $this->db->get("nhat_ki_hanh_trinh")->result();
        $rows =  array();

        foreach($objects as $obj)
        {
            $cell = array();
                            array_push($cell, $obj->STT_NKHT);
                            array_push($cell, $obj->SO_DANG_KY_XE);
                            array_push($cell, $obj->TEN);
                            array_push($cell, $obj->diemdiemKH);
                            array_push($cell, $obj->diemdiemKT);
                            array_push($cell, $obj->NGAY_KHOI_HANH);
                            array_push($cell, $obj->NGAY_KET_THUC_DK);
                            array_push($cell, $obj->NGAY_KET_THUC);
                        $row = new stdClass();
            $row->id = $cell[0];
            $row->cell = $cell;
            array_push($rows, $row);
        }

        $jsonObject = new stdClass();
        $jsonObject->page =  $page;
        $jsonObject->total = $total_pages;
        $jsonObject->records = $count;
        $jsonObject->rows = $rows;      



        return $jsonObject;
    }

    function save()
    {
        // When we insert or update a record in CodeIgniter, we pass the results as an array:
        $db_array = array(
                    "SO_DANG_KY_XE" => $this->SO_DANG_KY_XE,
                    "TEN" => $this->TEN,
                    "diemdiemKH" => $this->diemdiemKH,
                    "diemdiemKT" => $this->diemdiemKT,
                    "NGAY_KHOI_HANH" => $this->NGAY_KHOI_HANH,
                    "NGAY_KET_THUC_DK" => $this->NGAY_KET_THUC_DK,
                    "NGAY_KET_THUC" => $this->NGAY_KET_THUC,
          );

      $saveSuccess = false;

         // If key was set in the controller, then we will update an existing record.
        if ($this->STT_NKHT)
        {
            $this->db->trans_start();
            $this->db->where("STT_NKHT", $this->STT_NKHT);
            $this->db->update("nhat_ki_hanh_trinh", $db_array);
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
            $this->db->trans_complete();
        }
         // If key was not set in the controller, then we will insert a new record.
        else
        {
            $this->db->trans_start();
            $this->db->insert("nhat_ki_hanh_trinh", $db_array);
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
            $this->db->trans_complete();
         }
        
        return $saveSuccess;
    }


    function delete()
    {
        $saveSuccess = false;
         // As long as nhat_ki_hanh_trinh->STT_NKHT was set in the controller, we will delete the record.
        if ($this->STT_NKHT) {
            $this->db->where("STT_NKHT", $this->STT_NKHT);
            $this->db->delete("nhat_ki_hanh_trinh");
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
        }
                return $saveSuccess;
    }
}

?>