<?php echo "<?php"?>

//Controller is generated by MVC Schema Engine

/**
* @property CI_Loader $load
* @property CI_Form_validation $form_validation
* @property CI_Input $input
* @property CI_Email $email
* @property CI_DB_active_record $db
* @property CI_DB_forge $dbforge
* @property VehicleDBUtils $VehicleDBUtils
* @property <?=ucwords($object_name)?> $<?=($object_name)?>
*/ 

class c_<?=ucwords($object_name)?> extends Controller
{
    //message in vietnamese, TODO: add I18N later
    var $messageSuccess = "Thành công";
    var $messageFail    = "Thất bại";

    function c_<?=ucwords($object_name)?>()
    {
         parent::Controller();
         $this->load->model('<?=$object_name?>');
         $this->load->model('VehicleDBUtils');

         $this->load->helper('form');
         $this->load->helper('object2array');
         $this->load->library('form_validation');
    }

    function index()
    {       
        $this->load->view('scaffolding_form/v_<?=$object_name?>');        
    }  

    function read<?=ucwords($object_name)?>($priKey)
    {
        if(isset ($priKey))
        {
        <?php foreach($fields as $field):?>
        <?php if($field->isKey): ?>
   $this-><?=$object_name?>-><?=$field->name?> = $priKey;
        <?php endif;?>
        <?php endforeach;?>

            $rows = $this-><?=$object_name?>->read();
            foreach($rows as $row)
            {
            <?php foreach($fields as $field):?>
            echo $row-><?=$field->name?>."<br>";
            <?php endforeach;?>
            }
         }
    }

    function create()
    {
    <?php foreach($fields as $field):?>
    <?php if(!$field->isKey): ?>
        $this-><?=$object_name?>-><?=$field->name?> = $this->input->xss_clean($this->input->post('<?=$field->name?>'));
    <?php endif;?>
    <?php endforeach;?>
    
    if($this-><?=$object_name?>->save())
        echo $this->messageSuccess;
    else
        echo $this->messageFail;         
      
    }

    function read()
    {
        $this->load->view('v_<?=$object_name?>');
    }

    function read_json_format()
    {
        echo json_encode($this-><?=$object_name?>->readByPagination());
    }

    function update()
    {
    <?php foreach($fields as $field):?>
    $this-><?=$object_name?>-><?=$field->name?> = $this->input->xss_clean($this->input->post('<?=$field->name?>'));
    <?php endforeach;?>
       
        if($this-><?=$object_name?>->save())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;
        
    }

    function delete()
    {
    <?php foreach($fields as $field):?>
    <?php if($field->isKey): ?>
    $this-><?=$object_name?>-><?=$field->name?> = $this->input->xss_clean($this->input->post('<?=$field->name?>'));
    <?php endif;?>
    <?php endforeach;?>

        if($this-><?=$object_name?>->delete())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;
        
    }


    
}
<?php echo "?>"?>
