<html>
    <head>

        <!-- View is generated by MVC Schema Engine -->

        <base href="<?php echo base_url()?>">
        <title><?=ucwords($object_name)?></title>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />

        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo base_url()?>resources/jqGrid/themes/basic/grid.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo base_url()?>resources/theme/ui.all.css"  />
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo base_url()?>resources/css/main-app.css"  />
        <style type="text/css">
            .toggler { width: 250px; height: 125px; }
            #drop { width: 240px; height: 105px; padding: 0.4em; }
            #drop .ui-widget-header { margin: 0; padding: 0.4em; text-align: center; }
        </style>

        <script type="text/javascript" src="<?php echo base_url()?>resources/jquery-1.3.1.js"></script>
        <script type="text/javascript" src="<?php echo base_url()?>resources/jquery.ui.all.js"></script>
        <script type="text/javascript" src="<?php echo base_url()?>resources/jqGrid/jquery.jqGrid.js"></script>

        <!--  Utils for Page -->
        <script type="text/javascript" src="<?php echo base_url()?>resources/utils/inlinebox.js"></script>
        <script type="text/javascript" src="<?php echo base_url()?>resources/utils/jquery.form.js"></script>
        <script type="text/javascript" src="<?php echo base_url()?>resources/utils/jquery.field.min.js"></script>
        <script type="text/javascript" src="<?php echo base_url()?>resources/utils/jquery.validate.js"></script>
        <script type="text/javascript" src="<?php echo base_url()?>resources/utils/jquery.autocomplete.js"></script>
        <script type="text/javascript" src="<?php echo base_url()?>resources/utils/jquery.maskedinput-1.2.1.pack.js"></script>


        <script  type="text/javascript">
            var <?=ucwords($object_name)?> = {};

<?=ucwords($object_name)?>.data = {};
<?=ucwords($object_name)?>.setDataField = function(fieldName,fieldValue)
    {
<?=ucwords($object_name)?>.data[fieldName] = fieldValue;
    }

<?=ucwords($object_name)?>.setData = function(data)
    {
        jQuery.each(data, function(name, value) {
<?=ucwords($object_name)?>.data[name] = value;
            $('#main_form [name='+ name +']').val( value );
        });
    }


<?=ucwords($object_name)?>.getData = function()
    {
        var obj = {};
        $.each( $("#main_form").formSerialize().split("&"), function(i,n)
                        {
                            var toks = n.split("=");
                            obj[toks[0]] = toks[1];
                        }
        );
        <?=ucwords($object_name)?>.data = obj;
        return <?=ucwords($object_name)?>.data;
    }

    //create
<?=ucwords($object_name)?>.Create = function()
    {
        if(!$("#main_form").valid())
            return;
        InlineBox.showAjaxLoader();
        jQuery.post("<?php echo site_url("$object_name")?>_c/create", <?=ucwords($object_name)?>.getData() ,
        function(message){
            if(message != null){
                InlineBox.hideAjaxLoader();
                $("#list2").trigger("reloadGrid");
                InlineBox.showModalBox("Tạo <?=ucwords($object_name)?> " + message);
            }
        });
    }

    //refresh grid
<?=ucwords($object_name)?>.Read = function()
    {
        InlineBox.showAjaxLoader();
        jQuery.post("<?php echo site_url("$object_name")?>_c/read_json_format", {},
        function(data){
            InlineBox.hideAjaxLoader();
            $("#list2").trigger("reloadGrid");
        });
    }

    //update
<?=ucwords($object_name)?>.Update = function()
    {
        if(!$("#main_form").valid())
            return;

        InlineBox.showAjaxLoader();
        jQuery.post("<?php echo site_url("$object_name")?>_c/update", <?=ucwords($object_name)?>.getData() ,
        function(message){
            InlineBox.hideAjaxLoader();
            $("#list2").trigger("reloadGrid");
            InlineBox.showModalBox("Cập nhật <?=ucwords($object_name)?> " + message);
        });
    }


    //delete
<?=ucwords($object_name)?>.Delete = function()
    {
        if(!$("#main_form").valid())
            return;
        InlineBox.showAjaxLoader();
        jQuery.post("<?php echo site_url("$object_name")?>_c/delete",<?=ucwords($object_name)?>.getData() ,
        function(message){
            InlineBox.hideAjaxLoader();
            $("#list2").trigger("reloadGrid");
            InlineBox.showModalBox("Xoá <?=ucwords($object_name)?> " + message);
        });
    }

<?=ucwords($object_name)?>.currentRowID = null;

<?=ucwords($object_name)?>.setSelectedRow = function(id)
    {
<?=ucwords($object_name)?>.currentRowID = id;
    }

    var inputDate = {};
    $( function() {
<?php foreach($fields as $field):?>
<?php if($field->isDate): ?>
        inputDate['<?=$field->name?>'] = $("#<?=$field->name?>").datepicker({dateFormat:"yy/mm/dd"});
        $('#<?=$field->name?>').mask('9999/99/99');
        $('#<?=$field->name?>').validate({rules:{ require: true, date: true}});
<?php endif; ?>
<?php endforeach;?>
    });
        </script>
    </head>

    <body>
        <?php echo("<?php echo validation_errors(); ?>") ?>

        <div style="width: 930px;">
            <div class="box">
                <h1> <?=ucwords($object_fullname)?> </h1>
                <hr>

                <form method="POST" id="main_form" action="<?php echo site_url("$object_name")?>_c/update">
                    <?php foreach($fields as $field):?>
                    <?php //if(!$field->isAutoIncrement): ?>
                    <label>
                        <span><?=$field->fullname?></span>
                        <input type="text" name="<?=$field->name?>" value="<?=$field->default?>" id="<?=$field->name?>" class="input-text" onchange="<?=ucwords($object_name)?>.setDataField(this.name,this.value);"  />
                    </label>
                    <?php //endif;?>
                    <?php endforeach;?>

                    <input type="radio" name="tt" value="1" />
                    <input type="radio" name="tt" value="2" />
                    <select name="ttt">
                        <option>1</option>
                        <option>2</option>
                        <option>3</option>
                    </select>

                    <input type="submit"  name="submitButton" value="Submit1" />
                </form>

                <div class="spacer" id="form_control" >
                    <a href="javascript:void(0)" onclick="<?=ucwords($object_name)?>.Create()" class="green">Thêm</a>
                    <a href="javascript:void(0)" onclick="<?=ucwords($object_name)?>.Update()" class="green">Cập nhập</a>
                    <a href="javascript:void(0)" onclick="<?=ucwords($object_name)?>.Delete()" class="green">Xoá</a>
                </div>
                <div id="ajaxloader" style="display:none" >
                    <img  src="<?php echo base_url()?>resources/css/img/ajax-loader.gif" />
                </div>
            </div>
            <hr>
            <div>
                <table id="list2" class="scroll" style="margin-top:8px;" cellpadding="0" cellspacing="0"></table>
                <div id="pager2" class="scroll" style="text-align:center;"></div>
            </div>
        </div>

        <h1>Output Div (#output1):</h1>
        <div id="output1">AJAX response will replace this content.</div>

        <p>
            <label>Image search (remote):</label>
            <input type="text" id='imageSearch' />
            <input type="button" value="Get Value" />
        </p>

        <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

        <?php echo form_open_multipart('upload/do_upload');?>

        <input type="file" name="userfile" size="20" />

        <br /><br />

        <input type="submit" value="upload" />

        <?php echo form_close() ?>


    </body>

    <script type="text/javascript">
        // $('#last_activity').val().toString()
        var jGrid = null;
        var colNamesT = new Array();
        var colModelT = new Array();
        var gridimgpath = '<?php echo base_url()?>resources/jqGrid/themes/basic/images';

<?php foreach($fields as $field):?>
    colNamesT.push('<?=$field->name?>');
    colModelT.push({name:'<?=$field->name?>',index:'<?=$field->name?>', editable: false});
<?php endforeach;?>

    var loadView = function()
    {
        jGrid = jQuery("#list2").jqGrid(
        {
            url:'<?php echo site_url("$object_name")?>_c/read_json_format',
            mtype : "POST",
            datatype: "json",
            colNames: colNamesT ,
            colModel: colModelT ,
            rowNum:10,
            height: 270,
            rowList:[10,20,30],
            imgpath: gridimgpath,
            pager: jQuery('#pager2'),
            sortname: colNamesT[0],
            viewrecords: true,
            caption:"<?=$object_fullname?>",
            onSelectRow: function(){
                var id = jQuery("#list2").getGridParam('selrow');
<?=ucwords($object_name)?>.setData(jQuery("#list2").getRowData(id));
            }
        });
        jGrid.navGrid('#pager2',{edit:false,add:false,del:false, search: false, refresh: true});
        $("#alertmod").remove();//FIXME
    }
    jQuery("#list2").ready(loadView);


    var initForm = function(){
        //init validation form
        $("#main_form").validate();

        //init input mask


        var options = {
            target:        '#output1',   // target element(s) to be updated with server response
            beforeSubmit:  showRequest,  // pre-submit callback
            success:       showResponse  // post-submit callback

            // other available options:
            //url:       url         // override for form's 'action' attribute
            //type:      type        // 'get' or 'post', override for form's 'method' attribute
            //dataType:  null        // 'xml', 'script', or 'json' (expected server response type)
            //clearForm: true        // clear all form fields after successful submit
            //resetForm: true        // reset the form after successful submit

            // $.ajax options can be used here too, for example:
            //timeout:   3000
        };

        // bind form using 'ajaxForm'
        $('#main_form').ajaxForm(options);


        $("#imageSearch").autocomplete("http://localhost/vehicle/index.php/zzz/findVehicle/", {
            width: 320,
            max: 4,
            highlight: false,
            scroll: true,
            scrollHeight: 300,
            formatItem: function(data, i, n, value) {
                return "<img width=90 height=60 src='resources/images/" + value + "'/> " +  value.split(".")[0];
            },
            formatResult: function(data, value) {
                return value.split(".")[0];
            }
        });

    }

    jQuery("#main_form").ready(initForm);

    // pre-submit callback
    function showRequest(formData, jqForm, options) {
        // formData is an array; here we use $.param to convert it to a string to display it
        // but the form plugin does this for you automatically when it submits the data
        var queryString = $.param(formData);

        // jqForm is a jQuery object encapsulating the form element.  To access the
        // DOM element for the form do this:
        // var formElement = jqForm[0];

        alert('About to submit: \n\n' + queryString);

        // here we could return false to prevent the form from being submitted;
        // returning anything other than false will allow the form submit to continue
        return true;
    }

    // post-submit callback
    function showResponse(responseText, statusText)  {
        // for normal html responses, the first argument to the success callback
        // is the XMLHttpRequest object's responseText property

        // if the ajaxForm method was passed an Options Object with the dataType
        // property set to 'xml' then the first argument to the success callback
        // is the XMLHttpRequest object's responseXML property

        // if the ajaxForm method was passed an Options Object with the dataType
        // property set to 'json' then the first argument to the success callback
        // is the json data object returned by the server

        alert('status: ' + statusText + '\n\nresponseText: \n' + responseText +
            '\n\nThe output div should have already been updated with the responseText.');
    }

    </script>

    <div class="info-box" id="info-box" style="display:none">
        <div class="toggler">
            <div id="drop" class="ui-widget-content ui-corner-all">
                <h3 class="ui-widget-header ui-corner-all" id="info-box-header">info box</h3>
                <p>
                    <div id="info-box-msg" align="center" style="font-size:13px;font-weight: bold;"> content </div>
                </p>
                <center>
                    <input type="button" value="Đóng" id="inform-box-close" onclick="$('.info-box').toggle('drop')" />
                </center>
            </div>
        </div>
    </div>
</html>